### ISSUE TITLE
Attribute error while installing poopler

### ISSUE THREAD

**Issue by Aditya-R-K** [cbrunet/python-poppler#31]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\adity\AppData\Local\Temp\pip-install-_ii9h7dq\python-poppler_c004275ea29e4cdbbb1a83cfed9b71c9\setup.py", line 76, in <module>
        setup(
      File "c:\program files\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\program files\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\adity\AppData\Local\Temp\pip-install-_ii9h7dq\python-poppler_c004275ea29e4cdbbb1a83cfed9b71c9\setup.py", line 24, in run
        out = subprocess.check_output(["cmake", "--version"])
      File "c:\program files\python39\lib\subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Users\adity\AppData\Roaming\Python\Python39\site-packages\run\__init__.py", line 145, in __new__
        process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
      File "C:\Users\adity\AppData\Roaming\Python\Python39\site-packages\run\__init__.py", line 121, in create_process
        shlex.split(command),
      File "c:\program files\python39\lib\shlex.py", line 315, in split
        return list(lex)
      File "c:\program files\python39\lib\shlex.py", line 300, in __next__
        token = self.get_token()
      File "c:\program files\python39\lib\shlex.py", line 109, in get_token
        raw = self.read_token()
      File "c:\program files\python39\lib\shlex.py", line 140, in read_token
        nextchar = self.instream.read(1)
    AttributeError: 'list' object has no attribute 'read'

**Comment by cbrunet** [comment]
Do you have the **subprocess.run** package installed? Please try to remove it and see if it solves the problem: `pip uninstall subprocess.run`

**Comment by mara004** [comment]
@cbrunet I think `subprocess` is not a package. It's a module that is part of the Python standard library.
