### ISSUE TITLE
install in ubuntu 22.04

### ISSUE THREAD

**Issue by anh-viet-dang** [cbrunet/python-poppler#59]
I tried to install in ubuntu22.04 and i have same problem #28 
I install [libpoppler-cpp-dev](https://zoomadmin.com/HowToInstall/UbuntuPackage/libpoppler-cpp-dev) and after that, everything work well
In this issue, I just want to say how I fix #28 
here is my console log
```
(avada) agent@tm:~/Downloads/python-poppler$ git submodule update --init --recursive
(avada) agent@tm:~/Downloads/python-poppler$ python setup.py install
running install
/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating src/python_poppler.egg-info
writing src/python_poppler.egg-info/PKG-INFO
writing dependency_links to src/python_poppler.egg-info/dependency_links.txt
writing top-level names to src/python_poppler.egg-info/top_level.txt
writing manifest file 'src/python_poppler.egg-info/SOURCES.txt'
reading manifest file 'src/python_poppler.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE.txt'
writing manifest file 'src/python_poppler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/poppler
copying src/poppler/document.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/utilities.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/toc.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/rectangle.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/__init__.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/page.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/pagerenderer.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/pagetransition.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/font.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/destination.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/image.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/embeddedfile.py -> build/lib.linux-x86_64-3.8/poppler
copying src/poppler/_version.py -> build/lib.linux-x86_64-3.8/poppler
creating build/lib.linux-x86_64-3.8/poppler/cpp
copying src/poppler/cpp/__init__.py -> build/lib.linux-x86_64-3.8/poppler/cpp
running build_ext
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- pybind11 v2.9.2 
-- Found PythonInterp: /home/agent/anaconda3/envs/avada/bin/python (found version "3.8.13") 
-- Found PythonLibs: /home/agent/anaconda3/envs/avada/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'poppler-cpp>=0.26.0'
--   No package 'poppler-cpp' found
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  CMakeLists.txt:14 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/agent/Downloads/python-poppler/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    setup(
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 68, in build_extension
    subprocess.check_call(
  File "/home/agent/anaconda3/envs/avada/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/agent/Downloads/python-poppler', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/agent/Downloads/python-poppler/build/lib.linux-x86_64-3.8/poppler/cpp', '-DPYTHON_EXECUTABLE=/home/agent/anaconda3/envs/avada/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
(avada) agent@tm:~/Downloads/python-poppler$ sudo apt-get update -y
Hit:1 http://vn.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://vn.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                                            
Hit:3 http://vn.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                                                          
Hit:4 http://vn.archive.ubuntu.com/ubuntu jammy-security InRelease                                                                                           
Hit:5 http://packages.microsoft.com/repos/code stable InRelease                                                                                              
Hit:6 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                
Hit:7 https://packages.microsoft.com/repos/edge stable InRelease                                                                                             
Hit:8 https://linux.teamviewer.com/deb stable InRelease                                                                                                      
Hit:9 https://download.sublimetext.com apt/stable/ InRelease                                                                              
Hit:10 https://ppa.launchpadcontent.net/bamboo-engine/ibus-bamboo/ubuntu jammy InRelease                           
Hit:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Ign:13 https://ppa.launchpadcontent.net/numix/ppa/ubuntu jammy InRelease
Hit:14 https://ppa.launchpadcontent.net/papirus/papirus/ubuntu jammy InRelease
Err:15 https://ppa.launchpadcontent.net/numix/ppa/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
W: https://linux.teamviewer.com/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://download.sublimetext.com/apt/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'https://ppa.launchpadcontent.net/numix/ppa/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
(avada) agent@tm:~/Downloads/python-poppler$ sudo apt-get install -y libpoppler-cpp-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  libmessaging-menu0
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  libpoppler-cpp-dev
0 upgraded, 1 newly installed, 0 to remove and 19 not upgraded.
Need to get 11,7 kB of archives.
After this operation, 89,1 kB of additional disk space will be used.
Get:1 http://vn.archive.ubuntu.com/ubuntu jammy/main amd64 libpoppler-cpp-dev amd64 22.02.0-2 [11,7 kB]
Fetched 11,7 kB in 1s (12,6 kB/s)             
Selecting previously unselected package libpoppler-cpp-dev:amd64.
(Reading database ... 392845 files and directories currently installed.)
Preparing to unpack .../libpoppler-cpp-dev_22.02.0-2_amd64.deb ...
Unpacking libpoppler-cpp-dev:amd64 (22.02.0-2) ...
Setting up libpoppler-cpp-dev:amd64 (22.02.0-2) ...
(avada) agent@tm:~/Downloads/python-poppler$ python setup.py install
running install
/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing src/python_poppler.egg-info/PKG-INFO
writing dependency_links to src/python_poppler.egg-info/dependency_links.txt
writing top-level names to src/python_poppler.egg-info/top_level.txt
reading manifest file 'src/python_poppler.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE.txt'
writing manifest file 'src/python_poppler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- pybind11 v2.9.2 
-- Checking for module 'poppler-cpp>=0.26.0'
--   Found poppler-cpp, version 22.02.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/agent/Downloads/python-poppler/build/temp.linux-x86_64-3.8
[  4%] Building CXX object CMakeFiles/global_.dir/src/cpp/global.cpp.o
[  8%] Building CXX object CMakeFiles/version.dir/src/cpp/version.cpp.o
[ 12%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/version.cpython-38-x86_64-linux-gnu.so
[ 12%] Built target version
[ 16%] Building CXX object CMakeFiles/rectangle.dir/src/cpp/rectangle.cpp.o
[ 20%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/global_.cpython-38-x86_64-linux-gnu.so
[ 20%] Built target global_
[ 25%] Building CXX object CMakeFiles/image.dir/src/cpp/image.cpp.o
[ 29%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/rectangle.cpython-38-x86_64-linux-gnu.so
[ 29%] Built target rectangle
[ 33%] Building CXX object CMakeFiles/document.dir/src/cpp/document.cpp.o
[ 37%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/image.cpython-38-x86_64-linux-gnu.so
[ 37%] Built target image
[ 41%] Building CXX object CMakeFiles/page.dir/src/cpp/page.cpp.o
[ 45%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/document.cpython-38-x86_64-linux-gnu.so
[ 45%] Built target document
[ 50%] Building CXX object CMakeFiles/page_renderer.dir/src/cpp/page_renderer.cpp.o
[ 54%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/page.cpython-38-x86_64-linux-gnu.so
[ 54%] Built target page
[ 58%] Building CXX object CMakeFiles/page_transition.dir/src/cpp/page_transition.cpp.o
[ 62%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/page_renderer.cpython-38-x86_64-linux-gnu.so
[ 62%] Built target page_renderer
[ 66%] Building CXX object CMakeFiles/embedded_file.dir/src/cpp/embedded_file.cpp.o
[ 70%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/page_transition.cpython-38-x86_64-linux-gnu.so
[ 70%] Built target page_transition
[ 75%] Building CXX object CMakeFiles/destination.dir/src/cpp/destination.cpp.o
[ 79%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/embedded_file.cpython-38-x86_64-linux-gnu.so
[ 79%] Built target embedded_file
[ 83%] Building CXX object CMakeFiles/toc.dir/src/cpp/toc.cpp.o
[ 87%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/toc.cpython-38-x86_64-linux-gnu.so
[ 87%] Built target toc
[ 91%] Building CXX object CMakeFiles/font.dir/src/cpp/font.cpp.o
[ 95%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/destination.cpython-38-x86_64-linux-gnu.so
[ 95%] Built target destination
[100%] Linking CXX shared module ../lib.linux-x86_64-3.8/poppler/cpp/font.cpython-38-x86_64-linux-gnu.so
[100%] Built target font
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/document.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/utilities.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/toc.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/rectangle.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/__init__.py -> build/bdist.linux-x86_64/egg/poppler
creating build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/image.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/page_renderer.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/destination.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/font.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/__init__.py -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/global_.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/version.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/page.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/toc.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/document.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/rectangle.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/page_transition.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/cpp/embedded_file.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/poppler/cpp
copying build/lib.linux-x86_64-3.8/poppler/page.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/pagerenderer.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/pagetransition.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/font.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/destination.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/image.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/embeddedfile.py -> build/bdist.linux-x86_64/egg/poppler
copying build/lib.linux-x86_64-3.8/poppler/_version.py -> build/bdist.linux-x86_64/egg/poppler
byte-compiling build/bdist.linux-x86_64/egg/poppler/document.py to document.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/utilities.py to utilities.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/toc.py to toc.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/rectangle.py to rectangle.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/cpp/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/page.py to page.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/pagerenderer.py to pagerenderer.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/pagetransition.py to pagetransition.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/font.py to font.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/destination.py to destination.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/image.py to image.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/embeddedfile.py to embeddedfile.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/poppler/_version.py to _version.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/python_poppler.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/python_poppler.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/python_poppler.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/python_poppler.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/python_poppler.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/python_poppler-0.3.0-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing python_poppler-0.3.0-py3.8-linux-x86_64.egg
creating /home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/python_poppler-0.3.0-py3.8-linux-x86_64.egg
Extracting python_poppler-0.3.0-py3.8-linux-x86_64.egg to /home/agent/anaconda3/envs/avada/lib/python3.8/site-packages
Adding python-poppler 0.3.0 to easy-install.pth file

Installed /home/agent/anaconda3/envs/avada/lib/python3.8/site-packages/python_poppler-0.3.0-py3.8-linux-x86_64.egg
Processing dependencies for python-poppler==0.3.0
Finished processing dependencies for python-poppler==0.3.0
(avada) agent@tm:~/Downloads/python-poppler$ 
```

**Comment by cbrunet** [comment]
Yes, you need the `libpoppler-cpp-dev` package, as stated in the documentation: https://cbrunet.net/python-poppler/installation.html#requirements . Thank you for sharing.
