### ISSUE TITLE
installation issue: can't build wheel for python-poppler

### ISSUE THREAD

**Issue by bzr1** [cbrunet/python-poppler#88]
im runing on mac intel

the output is :

Defaulting to user installation because normal site-packages is not writeable
Collecting python-poppler==0.3.0
  Using cached python-poppler-0.3.0.tar.gz (823 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: python-poppler
  Building wheel for python-poppler (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.6 /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/7z/f5yrvy6d489ctt6jnncd9yn40000gn/T/tmpgpdvlixh
       cwd: /private/var/folders/7z/f5yrvy6d489ctt6jnncd9yn40000gn/T/pip-install-oc4qvs72/python-poppler_d930c1d82b0346c29cf6165469df5d7f
  Complete output (85 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/toc.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/pagetransition.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/destination.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/_version.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/pagerenderer.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/page.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/font.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/document.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/rectangle.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/embeddedfile.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/utilities.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  copying src/poppler/image.py -> build/lib.macosx-10.9-x86_64-3.6/poppler
  creating build/lib.macosx-10.9-x86_64-3.6/poppler/cpp
  copying src/poppler/cpp/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/poppler/cpp
  running egg_info
  writing src/python_poppler.egg-info/PKG-INFO
  writing dependency_links to src/python_poppler.egg-info/dependency_links.txt
  writing top-level names to src/python_poppler.egg-info/top_level.txt
  reading manifest file 'src/python_poppler.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE.txt'
  writing manifest file 'src/python_poppler.egg-info/SOURCES.txt'
  running build_ext
  Traceback (most recent call last):
    File "setup.py", line 24, in run
      out = subprocess.check_output(["cmake", "--version"])
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
      restore_signals, start_new_session)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/private/var/folders/7z/f5yrvy6d489ctt6jnncd9yn40000gn/T/pip-build-env-_l32gwp0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/private/var/folders/7z/f5yrvy6d489ctt6jnncd9yn40000gn/T/pip-build-env-_l32gwp0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/7z/f5yrvy6d489ctt6jnncd9yn40000gn/T/pip-build-env-_l32gwp0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/7z/f5yrvy6d489ctt6jnncd9yn40000gn/T/pip-build-env-_l32gwp0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 108, in <module>
      zip_safe=False,
    File "/private/var/folders/7z/f5yrvy6d489ctt6jnncd9yn40000gn/T/pip-build-env-_l32gwp0/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/7z/f5yrvy6d489ctt6jnncd9yn40000gn/T/pip-build-env-_l32gwp0/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 28, in run
      + ", ".join(e.name for e in self.extensions)
  RuntimeError: CMake must be installed to build the following extensions: poppler.cpp.modules
  ----------------------------------------
  ERROR: Failed building wheel for python-poppler
Failed to build python-poppler
ERROR: Could not build wheels for python-poppler, which is required to install pyproject.toml-based projects

**Comment by TheMadMoose** [comment]
Getting a similar issue. Tried several versions, still not working. PIP indicates its a problem with the package :S

**Comment by mjaniec2013** [comment]
poppler installation fails on Windows 10 too.

pip install python-poppler

```
Collecting python-poppler
  Using cached python_poppler-0.4.1.tar.gz (138 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      + meson setup C:\Users\Pi\AppData\Local\Temp\pip-install-cnk2v67v\python-poppler_70d361b6b6dd42dc8efe3cb65580fcc1 C:\Users\Pi\AppData\Local\Temp\pip-install-cnk2v67v\python-poppler_70d361b6b6dd42dc8efe3cb65580fcc1\.mesonpy-lof45eua -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Pi\AppData\Local\Temp\pip-install-cnk2v67v\python-poppler_70d361b6b6dd42dc8efe3cb65580fcc1\.mesonpy-lof45eua\meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: C:\Users\Pi\AppData\Local\Temp\pip-install-cnk2v67v\python-poppler_70d361b6b6dd42dc8efe3cb65580fcc1
      Build dir: C:\Users\Pi\AppData\Local\Temp\pip-install-cnk2v67v\python-poppler_70d361b6b6dd42dc8efe3cb65580fcc1\.mesonpy-lof45eua
      Build type: native build
      Project name: python-poppler
      Project version: 0.4.1
      
      ..\meson.build:1:0: ERROR: Compiler cl cannot compile programs.
      
      A full log can be found at C:\Users\Pi\AppData\Local\Temp\pip-install-cnk2v67v\python-poppler_70d361b6b6dd42dc8efe3cb65580fcc1\.mesonpy-lof45eua\meson-logs\meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Windows 10
Python 3.12

**Comment by kknd4eva** [comment]
No solution to this? Facing the same issue.
